name: Motor Chakal App

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

# ESTO SOLUCIONA EL ERROR: Permiso explícito para que el bot pueda guardar
permissions:
  contents: write

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      # ESTO SOLUCIONA EL WARNING: Usamos la versión v4 en lugar de la v3
      - uses: actions/checkout@v4
      
      - name: Preparar motor de Chakal App
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar herramientas
        run: npm install
        
      - name: Extraer datos de FútbolFantasy
        run: node scraper.js
        
      - name: Guardar nuevo lineups.json en la base de datos
        run: |
          git config --global user.name "Chakal Bot"
          git config --global user.email "bot@chakalapp.com"
          git add lineups.json
          git commit -m "🛡️ Actualizando onces probables" || exit 0
          git push